name: Deploy
on: workflow_dispatch
concurrency:
  group: pages
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 17.5.0
      - run: npm ci
      - run: npm run build
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
