name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.5.0
      - run: npm ci
      - run: npm run build
