name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.5.0
      - run: npm ci
      - run: npm run fmt-check
      - run: npm run tsc
      # Ideally we would use this instead of have to build:
      # https://github.com/facebook/create-react-app/pull/11556
      - run: npm run build
